language: ruby

branches:
  except:
    - master

script: JEKYLL_ENV=production bundle exec jekyll build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: source
